version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: demo_backend_spring_boot
      MYSQL_USER: demo_backend_spring_boot
      MYSQL_PASSWORD: demo_backend_spring_boot
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - demo-network

  demo-backend-spring-boot:
    image: demo-backend-spring-boot
    container_name: demo-backend-spring-boot
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo_backend_spring_boot
      SPRING_DATASOURCE_USERNAME: demo_backend_spring_boot
      SPRING_DATASOURCE_PASSWORD: demo_backend_spring_boot
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "8080:8080"
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
